# Generated by Buildr 1.4.2, change to your liking
# Version number for this release
require 'buildr/scala'

VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "Steps"
COPYRIGHT = ""

SLF4J = 'org.slf4j:slf4j-log4j:jar:1.6.1'
LOG4J = 'log4j:log4j:1.2.15'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://ftp.cica.es/mirrors/maven2"
repositories.remote << "http://mirrors.ibiblio.org/pub/mirrors/maven2/"

desc "The Steps project"
define "Steps" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  resources
  test.resources

  compile.with LOG4J

end
